In [159]:
import numpy as np
import heapq
from typing import Union
from sklearn.metrics import pairwise_distances

class Graph:
    def __init__(self, adjacency_mat: Union[np.ndarray, str]):
        """ Unlike project 2, this Graph class takes an adjacency matrix as input. `adjacency_mat` 
        can either be a 2D numpy array of floats or the path to a CSV file containing a 2D numpy array of floats.

        In this project, we will assume `adjacency_mat` corresponds to the adjacency matrix of an undirected graph
        """
        if type(adjacency_mat) == str:
            self.adj_mat = self._load_adjacency_matrix_from_csv(adjacency_mat)
        elif type(adjacency_mat) == np.ndarray:
            self.adj_mat = adjacency_mat
        else: 
            raise TypeError('Input must be a valid path or an adjacency matrix')
        self.mst = None

    def _load_adjacency_matrix_from_csv(self, path: str) -> np.ndarray:
        with open(path) as f:
            return np.loadtxt(f, delimiter=',')

    def construct_mst(self):
        """ Given `self.adj_mat`, the adjacency matrix of a connected undirected graph, implement Prim's 
        algorithm to construct an adjacency matrix encoding the minimum spanning tree of `self.adj_mat`. 
            
        `self.adj_mat` is a 2D numpy array of floats. 
        Note that because we assume our input graph is undirected, `self.adj_mat` is symmetric. 
        Row i and column j represents the edge weight between vertex i and vertex j. An edge weight of zero indicates that no edge exists. 
        
        TODO: 
            This function does not return anything. Instead, store the adjacency matrix 
        representation of the minimum spanning tree of `self.adj_mat` in `self.mst`.
        We highly encourage the use of priority queues in your implementation. See the heapq
        module, particularly the `heapify`, `heappop`, and `heappush` functions.
        """
        print(self.adj_mat)
        # determine number of nodes, initialize mst as numpy array of zeros connecting all nodes
        num_nodes = np.shape(self.adj_mat)[1]
        self.mst = np.zeros(self.adj_mat.shape)
        
        # initialize a tree with a vertex closen arbitrarily from the graph
        vertices = list(range(num_nodes)) # create list with range of vertex numbers 
        curr_vertex = vertices[0]
        #curr_vertex = vertices.pop(0)  # determines current vertex and removes it from the list of remaining vertices
        visited_vertices = {curr_vertex}
        
        # store outgoing edges from visited_vertices as tuples in a priority queue, remove zeros
        outgoing_edges_with_zeros = list(self.adj_mat[1:num_nodes,curr_vertex])
        curr_vertex_list = [curr_vertex] * len(outgoing_edges_with_zeros)
        outgoing_edges_zip = list(zip(outgoing_edges_with_zeros, curr_vertex_list, vertices[1:]))
        outgoing_edges = [i for i in outgoing_edges_zip if i[0]!=0] # keep non-zero edges
        heapq.heapify(outgoing_edges)   
        
        # grow the tree by adding the minimum weight edge to a vertex not in the tree
        while(outgoing_edges):
            # determine lowest weighted edge and corresponding neighbor node
            lowest_weight_edge = heapq.heappop(outgoing_edges) # removes lowest weight edge from queue
            
            # if destination vertex isn't in vistited_vertices
            if lowest_weight_edge[2] not in visited_vertices:
                # Add this edge to our MST and add vertex to visited
                self.mst[lowest_weight_edge[1], lowest_weight_edge[2]] = lowest_weight_edge[0]
                self.mst[lowest_weight_edge[2], lowest_weight_edge[1]] = lowest_weight_edge[0]
                visited_vertices.add(lowest_weight_edge[2]) # Add the destination to visited_vertices
                # Add all outgoing edges from visited_vertices to our priority queue
                vertices_wo_current = [x for x in vertices if x!=curr_vertex] # vertices without current
                curr_vertex = lowest_weight_edge[2] # reset current vertex
                outgoing_edges_with_zeros = list(self.adj_mat[:,curr_vertex])
                outgoing_edges_with_zeros.pop(lowest_weight_edge[1]) # remove edge that led to this node from the other side  
                curr_vertex_list = [curr_vertex] * len(outgoing_edges_with_zeros)
                outgoing_edges_zip = list(zip(outgoing_edges_with_zeros, curr_vertex_list, vertices_wo_current)) 
                outgoing_edges_add = [i for i in outgoing_edges_zip if i[0]!=0] # keep non-zero edges
                for edge in outgoing_edges_add:
                    heapq.heappush(outgoing_edges, edge)
                print(self.mst)
        

small_graph = Graph("data/small.csv")
g=small_graph.construct_mst()



[[0. 5. 0. 5.]
 [5. 0. 1. 2.]
 [0. 1. 0. 4.]
 [5. 2. 4. 0.]]
[[0. 5. 0. 0.]
 [5. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 5. 0. 0.]
 [5. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 5. 0. 0.]
 [5. 0. 1. 2.]
 [0. 1. 0. 0.]
 [0. 2. 0. 0.]]


In [35]:
animals = ['dog', 'cat', 'dog', 'rabbit', 'dog', 'horse']

# get the index of 'dog'
index = animals.index('dog')


print(index)


0


In [45]:
numpy.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
file_path = './data/slingshot_example.txt'
# load coordinates of single cells in low-dimensional subspace
coords = np.loadtxt(file_path)
# compute pairwise distances for all 140 cells to form an undirected weighted graph
dist_mat = pairwise_distances(coords)  
#sub_dist_mat = dist_mat[0:5,0:5]

g = Graph(dist_mat)
g.construct_mst()


In [139]:
list(range(4))

[0, 1, 2, 3]